# Generated by Django 5.0.3 on 2024-05-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='total',
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
